version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      resource_class: medium
    steps:
      - checkout
      - run: docker build . -t ci
      - run: docker run -e GH_PERSONAL_TOKEN="${GH_PERSONAL_TOKEN}" -e TELEGRAM_TOKEN="${TELEGRAM_TOKEN}" ci
